
export const ProductDetails = [
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    },
    {
        img:"https://res.cloudinary.com/onetab/image/upload/v1606988388/1tab/products1tab/mrmfferbrvv4wcktwksp",
        name:"MEDICINE NAME",
        mg:"30",
        ingredients:"ingredients",
        price:"price",
    }
]